language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: PHPCS=1
  allow_failures:
    - php: 7.0

before_script:
  - COMPOSER_ROOT_VERSION=dev-master
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE quick_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE quick_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE quick_test2;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE quick_test2;' -U postgres; fi"
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --ignore=*/Lib/*,*fixture/*,*webroot/*,*config/*,*aop/* --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./plugins; fi"

notifications:
  email: false
