language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

services:
  - memcached
  - redis-server

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: PHPCS=1
    - php: hhvm-nightly
      env: HHVM=1 DB=sqlite
    - php: hhvm-nightly
      env: HHVM=1 DB=mysql
  allow_failures:
    - php: hhvm-nightly
    - env: DB=pgsql
    - php: 7.0

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE quick_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE quick_test;' -U postgres; fi"
  - sh -c "if [ '$HHVM' != '1' ]; then echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --ignore=*/Lib/* --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./plugins; fi"

notifications:
  email: false
